// Minimal shim for Next.js RouteContext — the real definition lives in
// .next/dev/types/routes.d.ts (generated by `next dev`).  This shim keeps
// `tsc --noEmit` clean when .next hasn't been built yet.
declare type RouteContext<T extends string = string> = {
  params: Promise<Record<string, string>>;
};
